### PR TITLE
Fix stuff

### PR DESCRIPTION
**Pull request by om3ga6400**

### CODE REVIEW

**Comment by om3ga6400** [comment]
fix everything and removed weird broken fire gif you added

**Comment by om3ga6400** [comment]
@LordValkyrie

**Comment by om3ga6400** [comment]
also the streak stats are hosted by me so don't change the om3ga6400 in the URL like you did before I fixed it.

**Comment by om3ga6400** [comment]
ever time you edit yours I have to update this pull reqest until you merge it

**Comment by om3ga6400** [comment]
@LordValkyrie bro the discord thing is not just a shield badge I'll send the repo for you to do it

**Comment by om3ga6400** [comment]
@LordValkyrie https://github.com/gitlimes/discord-md-badge

**Comment by om3ga6400** [comment]
also this fixes the weird capital letters you added

**Comment by LordValkyrie** [comment]
ok

**Review by LordValkyrie — APPROVED** [review]

**Comment by om3ga6400** [comment]
@LordValkyrie merge it

**Comment by om3ga6400** [comment]
@LordValkyrie MERGE IT

**Comment by LordValkyrie** [comment]
ok

**Comment by LordValkyrie** [comment]
monke

**Pull request merged**
